---
- name: Install general packages on all hosts
  hosts: all
  roles:
    - common

- name: Configure backend
  hosts: backend
  roles:
    - backend

- name: Configure web
  hosts: web
  roles:
    - web